# Generated by Django 5.2 on 2025-04-12 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog1', '0007_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
