# Generated by Django 5.2 on 2025-04-13 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog1', '0008_article_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendedTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Writer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='writers/')),
                ('bio', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
