# Generated by Django 5.2 on 2025-04-13 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog1', '0009_recommendedtopic_writer'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='is_trending',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='read_time',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
