# Generated by Django 5.2 on 2025-04-14 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog1', '0010_blog_is_trending_alter_blog_image_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='tags',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
