# Generated by Django 5.2 on 2025-04-14 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog1', '0011_blog_tags'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='recommendedtopic',
            table='RecommendedTopic',
        ),
    ]
