# Generated by Django 5.2 on 2025-04-14 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog1', '0012_alter_recommendedtopic_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='recommendedtopic',
            table='blog1_RecommendedTopic',
        ),
    ]
