# Generated by Django 5.2 on 2025-05-04 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog1', '0013_alter_recommendedtopic_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='read_time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
