# Generated by Django 5.2 on 2025-05-07 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog1', '0015_comment_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('user', 'User')], default='user', max_length=20),
        ),
    ]
