# Generated by Django 5.2 on 2025-04-11 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrendingBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('read_time', models.IntegerField()),
                ('author_image', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('profile_image', models.ImageField(default='default_profile.jpg', upload_to='profile_pics')),
                ('skills', models.TextField(blank=True)),
                ('interests', models.TextField(blank=True)),
                ('is_profile_complete', models.BooleanField(default=False)),
                ('following', models.ManyToManyField(blank=True, related_name='blog2_followers', to='blog2.profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='blog2_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
